name: Cross-Platform Package Release

on:
  push:
    tags:
      - '*'

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install cx_Freeze
        run: pip install cx_Freeze

      - name: Freeze Python Script
        run: cxfreeze -c app.py --target-dir trackenn --target-name trackenn

      - name: Copy directories and files
        run: |
          cp -r front trackenn/
          cp -r data trackenn/
          cp config.yaml trackenn/

      - name: Zip Distribution Directory
        run: zip -r trackenn-linux.zip trackenn/

      - name: Upload Linux Asset
        uses: actions/upload-artifact@v2
        with:
          name: trackenn-linux.zip
          path: trackenn-linux.zip

  windows-build:
    runs-on: windows-latest
    needs: linux-build
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install cx_Freeze
        run: pip install cx_Freeze

      - name: Freeze Python Script
        run: cxfreeze -c app.py --target-dir trackenn --target-name trackenn

      - name: Copy directories and files
        run: |
          Copy-Item -Path front -Destination trackenn/ -Recurse
          Copy-Item -Path data -Destination trackenn/ -Recurse
          Copy-Item -Path config.yaml -Destination trackenn/

      - name: Zip Distribution Directory
        run: Compress-Archive -Path trackenn/* -DestinationPath trackenn-windows.zip

      - name: Upload Windows Asset
        uses: actions/upload-artifact@v2
        with:
          name: trackenn-windows.zip
          path: trackenn-windows.zip

  create-release:
    needs: [linux-build, windows-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: List files in the current directory
        run: ls -la

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (Linux)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./trackenn-linux.zip
          asset_name: trackenn-linux.zip
          asset_content_type: application/zip

      - name: Upload Release Asset (Windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./trackenn-windows.zip
          asset_name: trackenn-windows.zip
          asset_content_type: application/zip

